# This file was generated by agent-recall's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "0.2.0";
  base = "https://github.com/babarot/agent-recall/releases/download/${version}";
  assets = {
    aarch64-darwin = {
      name = "agent-recall-darwin-arm64";
      sha256 = "c1bdb2d697903d4accbac56e0b85280bc395038eb3cffe44b107a05a3f2de4a6";
    };
    x86_64-darwin = {
      name = "agent-recall-darwin-x86_64";
      sha256 = "b5bb75ef2f931a72d6899ed3015107dc7b8cab6187b9dcc9d2fe75f9ec1b676b";
    };
    aarch64-linux = {
      name = "agent-recall-linux-arm64";
      sha256 = "2b69e003e7767377d9b392aa1aff31f9947dbb322a4b8b7efb72cd4f7d495326";
    };
    x86_64-linux = {
      name = "agent-recall-linux-x86_64";
      sha256 = "031d10f3f661c5cd6acd5a36b3a7581a09a0333df46ee08999348950b4304a49";
    };
  };
  asset = assets.${system} or (throw "agent-recall: unsupported system ${system}");
  plugin = fetchurl {
    url = "${base}/agent-recall-plugin.tar.gz";
    sha256 = "a39c8a8987d5db34abc89cda540c5f3ef7d2063b16e58e03f5b5c663f6280464";
  };
in
stdenvNoCC.mkDerivation {
  pname = "agent-recall";
  inherit version;

  src = fetchurl {
    url = "${base}/${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # deno compile appends the program to the executable; stripping or
  # other fixups would break it
  dontFixup = true;

  # The Claude Code plugin (MCP server, SessionEnd hook, skills) lands in
  # share/claude-plugin/agent-recall; its skills are under skills/<name>
  installPhase = ''
    install -Dm755 $src $out/bin/agent-recall
    mkdir -p $out/share/claude-plugin/agent-recall
    tar -xzf ${plugin} -C $out/share/claude-plugin/agent-recall
  '';

  meta = {
    description = "Archive and search coding agent sessions";
    homepage = "https://github.com/babarot/agent-recall";
    mainProgram = "agent-recall";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
