# This file was generated by agent-recall's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "0.1.1";
  base = "https://github.com/babarot/agent-recall/releases/download/${version}";
  assets = {
    aarch64-darwin = {
      name = "agent-recall-darwin-arm64";
      sha256 = "8e0ab8ad1a144cb5e4678261b9bd67f1a42f00eb80d244bb2e1fd32d0ed13fe8";
    };
    x86_64-darwin = {
      name = "agent-recall-darwin-x86_64";
      sha256 = "15eb0ef23cdfbe6d76b40031c8a564d2e7c0df17577e05a5e9e191dca79cef96";
    };
    aarch64-linux = {
      name = "agent-recall-linux-arm64";
      sha256 = "35f30a6278f55e87edf2354ce61805c3ddbd87913532f6cffd4b3b8f680960d5";
    };
    x86_64-linux = {
      name = "agent-recall-linux-x86_64";
      sha256 = "5c6f36a5c63cc3b8caff9fc81935d2f9a7644c237add068ac77f284b6f5d175d";
    };
  };
  asset = assets.${system} or (throw "agent-recall: unsupported system ${system}");
  skills = fetchurl {
    url = "${base}/agent-recall-skills.tar.gz";
    sha256 = "46f164d77fd3e388a3c82463285b5d86d03b7c824bcb407091ff425d04b3c2a7";
  };
in
stdenvNoCC.mkDerivation {
  pname = "agent-recall";
  inherit version;

  src = fetchurl {
    url = "${base}/${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # deno compile appends the program to the executable; stripping or
  # other fixups would break it
  dontFixup = true;

  # Agent Skills land in share/skills/agent-recall/<name>/SKILL.md
  installPhase = ''
    install -Dm755 $src $out/bin/agent-recall
    mkdir -p $out/share/skills/agent-recall
    tar -xzf ${skills} -C $out/share/skills/agent-recall --strip-components=1
  '';

  meta = {
    description = "Archive and search coding agent sessions";
    homepage = "https://github.com/babarot/agent-recall";
    mainProgram = "agent-recall";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
