# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1wjxbrgpdyh2g640s759yz6yxyj0vcasf9y1ms7qcyysjzmkrs1i";
    aarch64-linux = "1f1vswacpbwal3v29jv4mbxjvv75sm1sjgrqppv8pnn6ygklrq0a";
    x86_64-darwin = "0rk0619fq6ix8q2py8yg7pkhxbg6k3i7a39y0xim5qy1x6nq10xv";
    aarch64-darwin = "0xxl4xpqiczj2d1871cw7ji1ivbai4y0irrh4g7zdyjzycxllm28";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/gh-infra/releases/download/v0.15.2/gh-infra_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/babarot/gh-infra/releases/download/v0.15.2/gh-infra_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/gh-infra/releases/download/v0.15.2/gh-infra_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/gh-infra/releases/download/v0.15.2/gh-infra_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gh-infra";
  version = "0.15.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./gh-infra $out/bin/gh-infra
    runHook postInstall
  '';

  meta = {
    description = "A gh extension for infrastructure management";
    homepage = "https://github.com/babarot/gh-infra";
    license = lib.licenses.mit;
    mainProgram = "gh-infra";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
