# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "040zklq90b0rp39n7p9vxrvgm1ixlmnbp5lgjv1qyxhlykxbdnrb";
    aarch64-linux = "02pqig90029qgcjsv4lrm3pxm7h6mk0i6scd58b9cg9m40ld03bb";
    x86_64-darwin = "1izymvrcxg4cbra2xbm5025676k56nvvyf07vj1vc63agmpmzx6j";
    aarch64-darwin = "0rn4g4146ix950qw7ydsdlwhsdzqjn58v1sxgrmmg46gx7p6l8b5";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/gh-infra/releases/download/v0.14.1/gh-infra_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/babarot/gh-infra/releases/download/v0.14.1/gh-infra_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/gh-infra/releases/download/v0.14.1/gh-infra_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/gh-infra/releases/download/v0.14.1/gh-infra_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gh-infra";
  version = "0.14.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./gh-infra $out/bin/gh-infra
    runHook postInstall
  '';

  meta = {
    description = "A gh extension for infrastructure management";
    homepage = "https://github.com/babarot/gh-infra";
    license = lib.licenses.mit;
    mainProgram = "gh-infra";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
