# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "17l0jaxzz91pm7fibdv69ma0xz29935s8wlsrkmxgaknzzj3022m";
    aarch64-linux = "09a8q708q7gz7fp2031nibnxah65pkc10z49j7fkw0sr5irwpzk0";
    x86_64-darwin = "0znx34hlznlbf1i6skb9v2228lwc5ic71ayim9d7z7rksjwvq0cz";
    aarch64-darwin = "10qggnxc2a0vfr0a9h2h9jbrjxq3w5v7r66kvfn373qq1qzm7nbw";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/gh-infra/releases/download/v0.15.0/gh-infra_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/babarot/gh-infra/releases/download/v0.15.0/gh-infra_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/gh-infra/releases/download/v0.15.0/gh-infra_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/gh-infra/releases/download/v0.15.0/gh-infra_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gh-infra";
  version = "0.15.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./gh-infra $out/bin/gh-infra
    runHook postInstall
  '';

  meta = {
    description = "A gh extension for infrastructure management";
    homepage = "https://github.com/babarot/gh-infra";
    license = lib.licenses.mit;
    mainProgram = "gh-infra";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
