# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "00dixwl4n5vk3xmb540s0fz9zamfrrb1ifnnvhqr81rcp007lci2";
    x86_64-linux = "0vsrzmpcz20lr71g1j94b549c7shbffylkb0mbjhrcb8wv14chsx";
    aarch64-linux = "1yyz01hjcrv2vqpm2gkjsspwiyinssi4fifwlh2rfs3xq373mcg5";
    x86_64-darwin = "1r7jqmrmxyax92qf0pv87yy83fnsbb4ad4bbi1p2chnc92dkmq4q";
    aarch64-darwin = "1yj2ygpijr9rw44if10znrdl408w6bwpkk0i1qsy6zykqzri3ip2";
  };

  urlMap = {
    i686-linux = "https://github.com/babarot/gist/releases/download/v1.2.8/gist_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/babarot/gist/releases/download/v1.2.8/gist_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/babarot/gist/releases/download/v1.2.8/gist_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/gist/releases/download/v1.2.8/gist_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/gist/releases/download/v1.2.8/gist_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gist";
  version = "1.2.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./gist $out/bin/gist
    runHook postInstall
  '';

  meta = {
    description = "A simple gist editor for CLI";
    homepage = "https://github.com/babarot/gist";
    license = lib.licenses.mit;
    mainProgram = "gist";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
