# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "124yj7jqq79maagswp06586p029mi1bcsvayrczh2jn4jlppmfak";
    x86_64-linux = "171hg75yh151zj5izpffa4pkz9b9gcp67005w2msd3y01q26agkv";
    aarch64-linux = "0hdyknkymp9q92km6r9bgm9jxi03n88nzqwlqbm2gcp03j8b2zcb";
    x86_64-darwin = "0326nidd12bm70x9wgv8lh4vkkx06jz4n2m1mypl1f7dqnb5xh16";
    aarch64-darwin = "0a10bvnvaw975dplx8d8icj9yinpr39hyqkc12d5q2jdz6gz1p0x";
  };

  urlMap = {
    i686-linux = "https://github.com/babarot/gist/releases/download/v1.2.7/gist_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/babarot/gist/releases/download/v1.2.7/gist_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/babarot/gist/releases/download/v1.2.7/gist_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/gist/releases/download/v1.2.7/gist_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/gist/releases/download/v1.2.7/gist_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gist";
  version = "1.2.7";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./gist $out/bin/gist
    runHook postInstall
  '';

  meta = {
    description = "A simple gist editor for CLI";
    homepage = "https://github.com/babarot/gist";
    license = lib.licenses.mit;
    mainProgram = "gist";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
