# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0l14qpdmllvbidsp5ygn4k4ps1mwb73yrpa4z2wh6bnlwp3gkbqa";
    x86_64-linux = "03k6gajz6kqs5bxhzpk1ggmx7pm5sdf96kd80px2rq82x9hhv50r";
    aarch64-linux = "1z4flavfc5gsvyd6lncwr87m5pgrndgknhh9x7gc7mmmszcb243m";
    x86_64-darwin = "0qbxs8j0p2r8i281srv1355abn40rsv6qavks46mplqvqcaycjis";
    aarch64-darwin = "1y9j2wl3m1axmc4dxj0iz7jjs46i8cyxirpv96cs3cplxc8yb5n6";
  };

  urlMap = {
    i686-linux = "https://github.com/babarot/blog/releases/download/v0.1.13/blog_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/babarot/blog/releases/download/v0.1.13/blog_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/babarot/blog/releases/download/v0.1.13/blog_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/blog/releases/download/v0.1.13/blog_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/blog/releases/download/v0.1.13/blog_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "blog";
  version = "0.1.13";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./blog $out/bin/blog
    runHook postInstall
  '';

  meta = {
    description = "Makes writing blogs easier";
    homepage = "https://github.com/babarot/blog";
    mainProgram = "blog";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
