# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "14l7b8w8sqa5cbhr3ryvxxyp7f806yjrbvnv1fhngz9w6pvm6af8";
    armv6l-linux = "0y6n4ail2y7zjp4ij68qn9fcilqplxpdbywpbn9yn6h30hfnfgpb";
    aarch64-linux = "1jvqi3ym2j0xw6d84x49xh086a65fw8wdmdijrclfyz35i4s05j6";
    x86_64-darwin = "07ivd017ma2034iy901y3gi1f8rm2ykn7j2q8dsilkrvgzhzkbfi";
    aarch64-darwin = "0vhkvxfr3s71458lgd1mmmqz97qyrvca99q649dqx7ap200wpw29";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/changed-objects/releases/download/v0.3.13/changed-objects_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/babarot/changed-objects/releases/download/v0.3.13/changed-objects_Linux_armv6.tar.gz";
    aarch64-linux = "https://github.com/babarot/changed-objects/releases/download/v0.3.13/changed-objects_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/changed-objects/releases/download/v0.3.13/changed-objects_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/changed-objects/releases/download/v0.3.13/changed-objects_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "changed-objects";
  version = "0.3.13";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./changed-objects $out/bin/changed-objects
    runHook postInstall
  '';

  meta = {
    description = "Get changed objects in Git commit";
    homepage = "https://github.com/babarot/changed-objects";
    mainProgram = "changed-objects";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
