# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1pljw71yfp05cng7xsxjwv53fjhdq9czpg4r216igi24nz3zmz2h";
    aarch64-linux = "1v2v1zl9m8f8mqhnkka41qnlbig41q9jdq4z49mjps129jdl395r";
    x86_64-darwin = "123ysqxqmiwvjmcs41fg09fk0ngny11ymnp1y0nhknp24zcivlrg";
    aarch64-darwin = "00c4xhsp522ma54kmg3iw8l4260rs25xwvka4q6cjawzl09yk4k7";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/enter/releases/download/v0.6.0/enter_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/babarot/enter/releases/download/v0.6.0/enter_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/enter/releases/download/v0.6.0/enter_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/enter/releases/download/v0.6.0/enter_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "enter";
  version = "0.6.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./enter $out/bin/enter
    runHook postInstall
  '';

  meta = {
    description = "Show contextual info when you press Enter on an empty prompt";
    homepage = "https://github.com/babarot/enter";
    license = lib.licenses.mit;
    mainProgram = "enter";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
