# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "017k8cjsx74zzfw2dwgrlw49mjp21vzgvxpp47mw83fkfnp0fqbq";
    aarch64-linux = "047z3wp306lxla37xsgjmxffq29d39q5l0b7iaz9i9y9ljingks4";
    x86_64-darwin = "0rv9cvs0yr5gf1fab9x0p66jqyg6hbxciv6yilwy9ha40hm16p7y";
    aarch64-darwin = "1zd5n98rq35qvv8s35fbjh7afx9capza795ad69i9f3c3r8g4wls";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/enter/releases/download/v0.5.0/enter_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/babarot/enter/releases/download/v0.5.0/enter_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/enter/releases/download/v0.5.0/enter_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/enter/releases/download/v0.5.0/enter_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "enter";
  version = "0.5.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./enter $out/bin/enter
    runHook postInstall
  '';

  meta = {
    description = "Show contextual info when you press Enter on an empty prompt";
    homepage = "https://github.com/babarot/enter";
    license = lib.licenses.mit;
    mainProgram = "enter";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
