# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  unzip,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "048fagamxbpp73qlywza4ak26znm9q33bd0lmc1v9kvi3zhy38r7";
    aarch64-linux = "1biibmrdcyamvdbpsq4z5prfaawnjc9jb1bmd7f8nhyml8i3kcyc";
    x86_64-darwin = "0cmwrr7jb80cjpzjcksafirmb11ndbwsvgngkabmx7j0bbkza3ga";
    aarch64-darwin = "0bgw0115i1jbijvbdd93q3f0w7h02r9aqcxi9hlc0srb8hi7jhiz";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Darwin_x86_64.zip";
    aarch64-darwin = "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Darwin_arm64.zip";
  };
in
stdenvNoCC.mkDerivation {
  pname = "naminator";
  version = "0.2.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles unzip ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./naminator $out/bin/naminator
    runHook postInstall
  '';

  meta = {
    description = "Bulk-rename w/ EXIF metadata";
    homepage = "https://github.com/babarot/naminator";
    license = lib.licenses.mit;
    mainProgram = "naminator";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
