# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  unzip,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1ah9ckcl9xv00ls0psnbid1zchjzdfpxyryk5pfhwymj76k120ja";
    aarch64-linux = "0sh2mqzv82zjvfc0y4r0aaq3dkvj5xgzgxcz8h11lgim9g1p2f4b";
    x86_64-darwin = "194hzc1amilmbkkn29hc6dcp4b2fdl71h76nypl79gn7f9pslwpx";
    aarch64-darwin = "1b6skqz1y8nm6m0hbi0f0ijw5ymfb2l1nwxapas49czgzd5i0zn8";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/naminator/releases/download/v0.2.6/naminator_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/babarot/naminator/releases/download/v0.2.6/naminator_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/naminator/releases/download/v0.2.6/naminator_Darwin_x86_64.zip";
    aarch64-darwin = "https://github.com/babarot/naminator/releases/download/v0.2.6/naminator_Darwin_arm64.zip";
  };
in
stdenvNoCC.mkDerivation {
  pname = "naminator";
  version = "0.2.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles unzip ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./naminator $out/bin/naminator
    runHook postInstall
  '';

  meta = {
    description = "Bulk-rename w/ EXIF metadata";
    homepage = "https://github.com/babarot/naminator";
    license = lib.licenses.mit;
    mainProgram = "naminator";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
