# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0c5qga6wm465zn2ml6nxwwlmqkyivx2gwwm30aqn275rvzil1bf2";
    aarch64-linux = "1dva5mki8d7cc85mnq7xhgqpp9sdzb96jahw3igm674sgf038043";
    x86_64-darwin = "1v0iigp6n03ihp43ysb9jb8hghqzf3f6vcshwlxnwp0adqm2cppp";
    aarch64-darwin = "0cimhx7mfgvvyc6jqn5hx8rwxggpy1mjs3h6j9xf0yyv1z8lm7sk";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/syno/releases/download/0.3.0/syno_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/babarot/syno/releases/download/0.3.0/syno_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/syno/releases/download/0.3.0/syno_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/syno/releases/download/0.3.0/syno_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "syno";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./syno $out/bin/syno
    mkdir -p $out/share/skills
    cp -r skills/syno $out/share/skills/syno
    runHook postInstall
  '';

  meta = {
    description = "Find the Synology NAS on your network and check on it from the terminal";
    homepage = "https://github.com/babarot/syno";
    license = lib.licenses.mit;
    mainProgram = "syno";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
