# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0ninf5cqxsihlgscha5c5fwclxavxxk7v0f0wzqvp2z2vawlcqy6";
    aarch64-linux = "0hw13xzv4x3wbdxsb7jb67w9dibg9wafk26iggq4wmgix5yp1rw7";
    x86_64-darwin = "02g4b9v0i625x7y9vv8l0y54yx523b20l6yrkad9nz9bfvk7rpyr";
    aarch64-darwin = "1cad5i8jx1ik6d809k7s09mrxbcis9dw60g7nsxcda3ka5z0aqw1";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/syno/releases/download/0.2.0/syno_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/babarot/syno/releases/download/0.2.0/syno_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/syno/releases/download/0.2.0/syno_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/syno/releases/download/0.2.0/syno_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "syno";
  version = "0.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./syno $out/bin/syno
    mkdir -p $out/share/skills
    cp -r skills/syno $out/share/skills/syno
    runHook postInstall
  '';

  meta = {
    description = "Find the Synology NAS on your network and check on it from the terminal";
    homepage = "https://github.com/babarot/syno";
    license = lib.licenses.mit;
    mainProgram = "syno";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
