# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0pvgc506vr3607snq3dk63j7jk7ri9xf1g9i16fyjwyw3b27pr63";
    aarch64-linux = "0hpqllm7s81vhx1s5qb6xcnl62m1h1glml8ha1xr3xslyvkgcczf";
    x86_64-darwin = "1qacpdpf5y57x24xs1c0zw1s9y2f11zqi9p4pdm0x1xy4zqkvklb";
    aarch64-darwin = "165w9irqdl7phnxif9xlabgc3m65xnbnxyvv5r87bl0jyddll2rp";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/syno/releases/download/v0.5.0/syno_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/babarot/syno/releases/download/v0.5.0/syno_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/syno/releases/download/v0.5.0/syno_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/babarot/syno/releases/download/v0.5.0/syno_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "syno";
  version = "0.5.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./syno $out/bin/syno
    mkdir -p $out/share/skills
    cp -r skills/syno $out/share/skills/syno
    runHook postInstall
  '';

  meta = {
    description = "Find the Synology NAS on your network and check on it from the terminal";
    homepage = "https://github.com/babarot/syno";
    license = lib.licenses.mit;
    mainProgram = "syno";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
