# This file was generated by c-c-statusline's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "0.3.1";
  assets = {
    aarch64-darwin = {
      name = "c-c-statusline-darwin-arm64";
      sha256 = "7f1f13b0ca34eda48870188bee99a8fc8e313493b2d432ce63b40cd601557b74";
    };
    x86_64-darwin = {
      name = "c-c-statusline-darwin-x86_64";
      sha256 = "341ab640e4fdd07ce80698847ebeb6db6a61a84cd439bb56211e01c18ee0a9e0";
    };
    aarch64-linux = {
      name = "c-c-statusline-linux-arm64";
      sha256 = "1f19daf98f5a9d2f7fa400ea584244de45372b0449603feb111b36ac7a61a768";
    };
    x86_64-linux = {
      name = "c-c-statusline-linux-x86_64";
      sha256 = "199638c3efffcf8d2d702c49ee6b32eaf5fa6933c930e11945fe4a01ea37179b";
    };
  };
  asset = assets.${system} or (throw "c-c-statusline: unsupported system ${system}");
in
stdenvNoCC.mkDerivation {
  pname = "c-c-statusline";
  inherit version;

  src = fetchurl {
    url = "https://github.com/babarot/c-c-statusline/releases/download/${version}/${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # deno compile appends the program to the executable; stripping or
  # other fixups would break it
  dontFixup = true;

  installPhase = ''
    install -Dm755 $src $out/bin/c-c-statusline
  '';

  meta = {
    description = "A Deno-powered status line for Claude Code CLI";
    homepage = "https://github.com/babarot/c-c-statusline";
    license = lib.licenses.mit;
    mainProgram = "c-c-statusline";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
