# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  unzip,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1gysmllyxdj629v37jc3mvywpf33h2416l4myz4ym55v0vv2gy18";
    aarch64-linux = "0mr4j44736pxvqv41p930abg5w5m9j8l87zshj5vbhyjv0ac434m";
    x86_64-darwin = "1rgs06v51jk46bskwg9rsi24h8x3vjh9w0snpljjjsrpgvk1mmp7";
    aarch64-darwin = "038p46nfy6djfymsv2y0w92fvlbcjgyxfd5b1z96yn64jiiv1nhd";
  };

  urlMap = {
    x86_64-linux = "https://github.com/babarot/mo/releases/download/v1.4.0/mo_v1.4.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/babarot/mo/releases/download/v1.4.0/mo_v1.4.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/babarot/mo/releases/download/v1.4.0/mo_v1.4.0_darwin_amd64.zip";
    aarch64-darwin = "https://github.com/babarot/mo/releases/download/v1.4.0/mo_v1.4.0_darwin_arm64.zip";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mo";
  version = "1.4.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles unzip ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./mo $out/bin/mo
    runHook postInstall
  '';

  meta = {
    description = "Markdown viewer that opens .md files in a browser (babarot's fork)";
    homepage = "https://github.com/babarot/mo";
    license = lib.licenses.mit;
    mainProgram = "mo";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
