# This file was generated by claude-recall's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "1.0.0";
  base = "https://github.com/babarot/claude-recall/releases/download/${version}";
  assets = {
    aarch64-darwin = {
      name = "claude-recall-darwin-arm64";
      sha256 = "2832a37f6bc1a8654fb08849d87829f987702674d3f38a7804e51b41d1dab061";
    };
    x86_64-darwin = {
      name = "claude-recall-darwin-x86_64";
      sha256 = "adc3dda9d031f9fcc46cda5da192faa0aa75308051d73d85b2874ccba2c994b0";
    };
    aarch64-linux = {
      name = "claude-recall-linux-arm64";
      sha256 = "3e6799d1ea8fa40561eb177d3d3f7189e770f089e0a50aff83726ee2fff03171";
    };
    x86_64-linux = {
      name = "claude-recall-linux-x86_64";
      sha256 = "9dd33d8fb88c334870e1312d39dbef908a6a6bda008ae9096b66e2cdb812bd26";
    };
  };
  asset = assets.${system} or (throw "claude-recall: unsupported system ${system}");
  plugin = fetchurl {
    url = "${base}/claude-recall-plugin.tar.gz";
    sha256 = "b553d3c17c31fe6e6e4b54ffce22237a480a3d4a9391a878ee886223102aae1a";
  };
in
stdenvNoCC.mkDerivation {
  pname = "claude-recall";
  inherit version;

  src = fetchurl {
    url = "${base}/${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # A static Go binary; stripping it again or patching it gains nothing
  dontFixup = true;

  # The Claude Code plugin (MCP server, SessionEnd hook, skills) lands in
  # share/claude-plugin/claude-recall; its skills are under skills/<name>
  installPhase = ''
    install -Dm755 $src $out/bin/recall
    mkdir -p $out/share/claude-plugin/claude-recall
    tar -xzf ${plugin} -C $out/share/claude-plugin/claude-recall
  '';

  meta = {
    description = "Archive and search coding agent sessions";
    homepage = "https://github.com/babarot/claude-recall";
    mainProgram = "recall";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
