# This file was generated by claude-recall's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "1.7.1";
  base = "https://github.com/babarot/claude-recall/releases/download/${version}";
  assets = {
    aarch64-darwin = {
      name = "claude-recall-darwin-arm64";
      sha256 = "c779b63558db53624d70ec80e0c91189e8304753abffe912f7e9cec93eae1607";
    };
    x86_64-darwin = {
      name = "claude-recall-darwin-x86_64";
      sha256 = "612ef1baad89acd06f2e3d938866eed8a8b5f9f2906335b8c6be756426f44cac";
    };
    aarch64-linux = {
      name = "claude-recall-linux-arm64";
      sha256 = "c1d5733149ecb7ce2c0019da6785fda4e7fea109b6127dbe23b6a101242757a8";
    };
    x86_64-linux = {
      name = "claude-recall-linux-x86_64";
      sha256 = "8f3fad6a53159ec939b6cbab3484a721dd6fc5620d28e3063180e3afae32a800";
    };
  };
  asset = assets.${system} or (throw "claude-recall: unsupported system ${system}");
  plugin = fetchurl {
    url = "${base}/claude-recall-plugin.tar.gz";
    sha256 = "4adaa46bb2bfb4a7be48da66bebdec1539c70a083332282c16e3fcbea97fe113";
  };
in
stdenvNoCC.mkDerivation {
  pname = "claude-recall";
  inherit version;

  src = fetchurl {
    url = "${base}/${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # A static Go binary; stripping it again or patching it gains nothing
  dontFixup = true;

  # The Claude Code plugin (MCP server, SessionEnd hook, skills) lands in
  # share/claude-plugin/claude-recall; its skills are under skills/<name>
  installPhase = ''
    install -Dm755 $src $out/bin/recall
    mkdir -p $out/share/claude-plugin/claude-recall
    tar -xzf ${plugin} -C $out/share/claude-plugin/claude-recall
  '';

  meta = {
    description = "Archive and search coding agent sessions";
    homepage = "https://github.com/babarot/claude-recall";
    mainProgram = "recall";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
