# This file was generated by claude-recall's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "1.3.1";
  base = "https://github.com/babarot/claude-recall/releases/download/${version}";
  assets = {
    aarch64-darwin = {
      name = "claude-recall-darwin-arm64";
      sha256 = "51f598efad6ce05cbeed462d2299fd8937425c17dfb8c440c6cb4c98eeeb1572";
    };
    x86_64-darwin = {
      name = "claude-recall-darwin-x86_64";
      sha256 = "f862feacf3d4049ebb595b6eedd935d1a7144d953914a06dbdac2a5c66fa1f53";
    };
    aarch64-linux = {
      name = "claude-recall-linux-arm64";
      sha256 = "418e8ac6a9c72180c9f263d3cca96ca845274aa02db5f1377e17709722063592";
    };
    x86_64-linux = {
      name = "claude-recall-linux-x86_64";
      sha256 = "03a08101af765b8cdf18def3fbd8827948bc754cfc070c5ef7a7458dd994c4fc";
    };
  };
  asset = assets.${system} or (throw "claude-recall: unsupported system ${system}");
  plugin = fetchurl {
    url = "${base}/claude-recall-plugin.tar.gz";
    sha256 = "98e4751e735aef47ee3f86a404b77450e82013899544bfc159f2d5b46f17fd65";
  };
in
stdenvNoCC.mkDerivation {
  pname = "claude-recall";
  inherit version;

  src = fetchurl {
    url = "${base}/${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # A static Go binary; stripping it again or patching it gains nothing
  dontFixup = true;

  # The Claude Code plugin (MCP server, SessionEnd hook, skills) lands in
  # share/claude-plugin/claude-recall; its skills are under skills/<name>
  installPhase = ''
    install -Dm755 $src $out/bin/recall
    mkdir -p $out/share/claude-plugin/claude-recall
    tar -xzf ${plugin} -C $out/share/claude-plugin/claude-recall
  '';

  meta = {
    description = "Archive and search coding agent sessions";
    homepage = "https://github.com/babarot/claude-recall";
    mainProgram = "recall";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
